name: Build JAR
on: [push, workflow_dispatch]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: mvn install

      - name:
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          prerelease: false
          files: target/*.jar         

      - uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 1
          delete_tags: true
          delete_tag_pattern: latest 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# on:
#   push: 
#     branches: 
#       - main
#       
#   workflow_dispatch:
#
      # - name: Build jar
      #   run: |
      #     javac -sourcepath ./src/ -d ./target/ ./src/Main.java
      #     jar cfe JBomberMan.jar Main ./target/*.class 

